### ISSUE TITLE
failed to create new symlink

### ISSUE THREAD

**Issue by songroom2016** [WiSaGaN/ctp-rs#17]
Compiling ctp-md v0.10.0 (/home/sg/ctp_rs/ctp-md)
error: failed to run custom build command for `ctp-md v0.10.0 (/home/sg/ctp_rs/ctp-md)`

Caused by:
  process didn't exit successfully: `/home/sg/ctp_rs/target/release/build/ctp-md-ffc752198c8da060/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'failed to create new symlink: Os { code: 17, kind: AlreadyExists, message: "File exists" }', src/libcore/result.rs:1188:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

**Comment by songroom2016** [comment]
Compiling ctp-trader v0.10.0 (/home/sg/ctp_rs/ctp-trader)
error: failed to run custom build command for `ctp-trader v0.10.0 (/home/sg/ctp_rs/ctp-trader)`

Caused by:
  process didn't exit successfully: `/home/sg/ctp_rs/target/release/build/ctp-trader-ed6bac3847ad9fd9/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/home/sg/ctp_rs/target/release/build/ctp-trader-40a515d8c5e36813/out

--- stderr
thread 'main' panicked at 'failed to copy so to outdir: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1188:5    
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
