### ISSUE TITLE
Cannot build on my Manjaro 18.1

### ISSUE THREAD

**Issue by keybatman** [WiSaGaN/ctp-rs#9]
I have tried to build [ctp-trader-v0.8.1](https://github.com/WiSaGaN/ctp-rs/releases/tag/ctp-trader-v0.8.1) for several time, but always encounter the same error (attached below).
Can you please help me to fix this?

Also, I am a newb to both `Rust` and `CTP`. So, sorry if this is a stupid question.

```
$ cargo build --release
   Compiling libc v0.2.65
   Compiling encoding_index_tests v0.1.4
   Compiling memchr v2.2.1
   Compiling simple-error v0.2.1
   Compiling ctp-trader v0.8.1 (~/ctp-rs-ctp-trader-v0.8.1/ctp-trader)
   Compiling ctp-md v0.8.0 (~/ctp-rs-ctp-trader-v0.8.1/ctp-md)
   Compiling encoding-index-japanese v1.20141219.5
   Compiling encoding-index-simpchinese v1.20141219.5
   Compiling encoding-index-korean v1.20141219.5
   Compiling encoding-index-tradchinese v1.20141219.5
   Compiling encoding-index-singlebyte v1.20141219.5
error: failed to run custom build command for `ctp-trader v0.8.1 (~/ctp-rs-ctp-trader-v0.8.1/ctp-trader)`

Caused by:
  process didn't exit successfully: `~/ctp-rs-ctp-trader-v0.8.1/target/release/build/ctp-trader-5bcd7ca2d0f9ca94/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=~/ctp-rs-ctp-trader-v0.8.1/target/release/build/ctp-trader-204f3bb4f27df520/out

--- stderr
thread 'main' panicked at 'failed to copy so to outdir: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by WiSaGaN** [comment]
```
--- stderr
thread 'main' panicked at 'failed to copy so to outdir: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1084:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
There was a failed attemp to copy the shared object file from the `api-ctp` folder, which is a git submodule from gitlab. Is this submodule initiated, e.g. does this directory contain the submodule repo? You can check https://www.vogella.com/tutorials/GitSubmodules/article.html for submodule reference.

**Comment by keybatman** [comment]
Yeah, It works!
Thank you very much for your quick and helpful reply @WiSaGaN
